### ISSUE TITLE
Problem with NopCommerce 3.70

### ISSUE THREAD

**Issue by hamid-gh** [mobsoftware/mobsocial#11]
It doesn't work with NopCommerce 3.70!
any updates?  

![image](https://cloud.githubusercontent.com/assets/11782611/12076589/0c176d00-b1c7-11e5-852d-6bf605a0c85c.png)

**Comment by mobsoftware** [comment]
Hi Hamid, did you pull the latest for Mob.Core and MobSocial? The new nopCommerce Register method has been implemented to include the new NopConfig parameter. Let us know. Thanks!

**Comment by hamid-gh** [comment]
Hi,
where is the latest for Mob.Core and MobSocial?
Please give me it's download link.

**Comment by mobsoftware** [comment]
https://github.com/mobsoftware/mob.core

And you will notice the base dependency registrar has been updated to account for the new NopConfig parameter below:
https://github.com/mobsoftware/mob.core/blob/master/BaseMobDependencyRegistrar.cs

**Comment by hamid-gh** [comment]
I installed it successfully but when i wanted to configure the plugin an error occurred: some Views (e.g. Configure.chtml) don't exist.
and now, the Public store don't working too. I receive the following error message:
The view 'MobAds.Public.Views.MobAds.AdDisplay' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Themes/MobSocialDefault/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Views/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: The view 'MobAds.Public.Views.MobAds.AdDisplay' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Themes/MobSocialDefault/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Views/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml

Source Error: 


Line 3:  @foreach (var widget in Model)
Line 4:  {
Line 5:      @Html.Action(widget.ActionName, widget.ControllerName, widget.RouteValues)
Line 6:  }

Source File: e:\rNovin\Projects\nopCommerce.Persian\nopCommerce_3.70_Source\Presentation\Nop.Web\Views\Widget\WidgetsByZone.cshtml    Line: 5

**Comment by mobsoftware** [comment]
Thanks hamid. We have not implemented the Configure screens. For now, things are configurable either in the Settings or directly using the Database. What kind of options are you looking to configure on the Configuration screen and we can implement them for you? Thanks

**Comment by hamid-gh** [comment]
Thanks a lot.
Ok, i don't need to configure screen. but now, the Public store don't working. I receive the following error message:
The view 'MobAds.Public.Views.MobAds.AdDisplay' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Themes/MobSocialDefault/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Views/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.InvalidOperationException: The view 'MobAds.Public.Views.MobAds.AdDisplay' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Themes/MobSocialDefault/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Administration/Views/Shared/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Views/MobAds.Public.Views.MobAds.AdDisplay.cshtml
~/Plugins/Widgets.mobSocial/Themes/MobSocialDefault/Views/MobAdsPublic/MobAds.Public.Views.MobAds.AdDisplay.cshtml

Source Error:

Line 3: @foreach (var widget in Model)
Line 4: {
Line 5: @Html.Action(widget.ActionName, widget.ControllerName, widget.RouteValues)
Line 6: }

Source File: \nopCommerce_3.70_Source\Presentation\Nop.Web\Views\Widget\WidgetsByZone.cshtml Line: 5
