### ISSUE TITLE
nopCommerce or standalone

### ISSUE THREAD

**Issue by 4lphac** [mobsoftware/mobsocial#12]
Sorry guys, I don't understand if this is a standalone platform or a nopCommerce plugin.

Thanks!

**Comment by mobsoftware** [comment]
Hi 4lphac, we are currently working on a standalone version. Are you in need of the standalone version?

Thanks,
Bruce

Bruce Leggett
MobSocial team

**Comment by 4lphac** [comment]
Yes, I was searching for an open source social based on .Net to extend and contribute for my needs and this one looks like the only option so far. I've seen in the readme that nopCommerce is still needed a requirement, are those just library dependencies or a full nopC install?

**Comment by mobsoftware** [comment]
It's depends on a full nopC install. nopC is a great platform with years of development. If you use it in combination with mobSocial, then you will have a social store that you can sell products and services with and mobSocial will provide you with more user interaction, resulting in increased sales and experience for your customers. The standalone version will most likely be ready sometime in June

**Comment by tsurf16** [comment]
Hi, I am also looking for a standalone version for my company.  Is there a way to contact you directly?  I would like to discuss our needs and see if you would be interested in helping us out on a contract basis?  Thanks!

**Comment by mobsoftware** [comment]
Hi tsurf16,

Yes, you can contact us directly at info@mobsocial.co; we can also help you
get set up and implement any features you need on a contract basis.

Thanks,
Bruce

mobSocial team
