### ISSUE TITLE
The type or namespace MobAds could not be found

### ISSUE THREAD

**Issue by nishant842** [mobsoftware/mobsocial#13]
I followed the instructions in ReadMe.txt. When trying to build 'Nop.Plugin.Widgets.MobSocial' I keep getting the error:

The type or namespace name 'MobAds' could not be found (are you missing a using directive or an assembly reference?)

**Comment by mobsoftware** [comment]
Hi Nishant, does the Nop.Plugin.Widgets.MobSocial project have a reference to "MobLib\MobAds.Public.dll"?

If so, what version of the .NET Framework is the project targeting; is it still version 4.5.1?

Thanks,
Bruce

**Comment by nishant842** [comment]
I am not sure what the reference was pointing to but it showed a yellow icon next to it. I removed the reference and added a reference to the one in the MobLib folder and it built successfully. 

After this everything installed successfully without errors but the Widget wouldn't show up. I enabled it in the admin panel and chaned the theme to mobSocial but still nothing.

**Comment by mobsoftware** [comment]
Is the MobSocialDefault theme in the nopCommerce Themes folder?

**Comment by mobsoftware** [comment]
Nishant, were you able to resolve this issue?

**Comment by nishant842** [comment]
No I wasn't. I decided to customize NopCommerce for my needs rather than
use a plugin so did not follow it up.
