### ISSUE TITLE
"My profile" cannot work

### ISSUE THREAD

**Issue by 102306071** [mobsoftware/mobsocial#18]
Hi,
After successfully installed the plugin, I found that the "My profile" page cannot work properly.
If I click the link, the page would be redirected to index page.
How can I fix this problem?

Thanks!

**Comment by wittyansh** [comment]
Hi, I believe you are talking about the [nopCommerce version](https://github.com/mobsoftware/mobSocial.nopCommercePlugin). For that please make sure that in Customer Settings, **Allow viewing of customer profiles** setting is enabled. If you continue to face issue, please create the issue in that repository.
