### ISSUE TITLE
help!!!!!

### ISSUE THREAD

**Issue by CS-begginer** [mobsoftware/mobsocial#19]
Hi.
How i can find Get start Documents?
I want try MobSocial with VS 2015 but have some error like this screen shot 
<img width="1680" alt="screen shot 1395-08-10 at 14 42 18" src="https://cloud.githubusercontent.com/assets/23167047/19852416/7058ef38-9f78-11e6-9d3c-2f485aabe4b9.png">
Please help!!! to Our Research

**Comment by mbuthiagrg** [comment]
Could provide a stack trace and more descriptive information about the error you are getting

**Comment by wittyansh** [comment]
Hi, please try the steps I mentioned at https://github.com/mobsoftware/mobsocial/issues/17#issuecomment-257271754
