### ISSUE TITLE
Having the error "The specified path, file name, or both are too long"

### ISSUE THREAD

**Issue by fairmaker** [mobsoftware/mobsocial#20]
When I execute the mobSocial webapp, I'm having the error. "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."

I can't get rid off of this error. I have the project in the root of my pc. C:\
Any ideas?

**Comment by mobsoftware** [comment]
Hi fairmaker, 

Can you copy and paste the build output here? We suspect this is occurring while trying to copy a module (e.g. node module) from one directory to another.

Thanks,
Bruce

**Comment by fairmaker** [comment]
It's weird, when I build the project there are no issues, It's only when i run the app.
There is one only error: 
 "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."

**Comment by wittyansh** [comment]
Hi Guys,
I've written some detailed[ How to install](https://github.com/mobsoftware/mobsocial/wiki/How-to-install-mobSocial%3F) instructions along with appropriate screenshots for setting up the environment and running the installation for mobSocial in the wiki. 

Please provide your feedback for the same.
