### ISSUE TITLE
Install page is not working

### ISSUE THREAD

**Issue by ins4n333** [mobsoftware/mobsocial#22]
I did everything actions by installation instruction, but when I open "Install" page I receive Internal Server Error (The requested page cannot be accessed because the related configuration data for the page is invalid.). There are no information about this error in EventLogs. I reproduced this error on 3 different isolated machines with different configuration (include Windows Server 2012 R2 in Microsoft Azure WM). I think that you forgot to add in instruction any required for install information.

In principle , because this time I tested in the cloud, I can provide you credentials for the RDP connection to the Azure WM, where I was testing it. This machine also include Visual Studion 2015 Community, IIS, git + with cloned  mobsocial repository. You can write me in skype ins_1986
Thanks!

**Comment by mobsoftware** [comment]
Hi ins4333, can you copy and paste the exception message and stacktrace here so we can help you troubleshoot?

Thanks!

**Comment by ins4n333** [comment]
Hi!
Unfortunately there are no information about this error in Event log (including the stack trace). This is an infrastructure configuration  problem. I.e. your installation instruction is not full.
I see only this : https://box.kaspersky.com/f/3921c6fb46/

**Comment by eretontali** [comment]
Yes, me too. Same problem :(

**Comment by wittyansh** [comment]
Hi, I think the problem is with the URL rewrite module. It's not installed by default on IIS 8. Can you please try downloading it from [here](https://www.iis.net/downloads/microsoft/url-rewrite). I think IIS is not recognizing the rewrite rules and that's why this error.

**Comment by ins4n333** [comment]
Its work for me. Thanks!
