### ISSUE TITLE
Facing Issue in installation

### ISSUE THREAD

**Issue by jaykumar-patel** [mobsoftware/mobsocial#23]
while adding db connection in installtion like below

![image](https://cloud.githubusercontent.com/assets/21011498/21225829/ae0b6b6e-c2f8-11e6-97e0-387246edaacb.png)

I am getting below error in Testing Database Connection

![image](https://cloud.githubusercontent.com/assets/21011498/21225794/883a62b4-c2f8-11e6-8d64-b47528ce0c7e.png)

**Comment by wittyansh** [comment]
Hi, Where do you get this error? Can you provide the stacktrace? Are you using the latest code?

**Comment by jaykumar-patel** [comment]
I get this error when I was trying to install it I am sending stack trace

**Comment by jaykumar-patel** [comment]
Server Error in '/api' Application.

The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.

Source Error: 


Line 10:     {
Line 11:        
Line 12:         public DatabaseContext(string nameOrConnectionString) : base(nameOrConnectionString)
Line 13:         {
Line 14:             Configuration.LazyLoadingEnabled = false;

Source File: C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Data\Database\DatabaseContext.cs    Line: 12 

Stack Trace: 


[ArgumentException: The argument 'nameOrConnectionString' cannot be null, empty or contain only white space.]
   System.Data.Entity.Utilities.Check.NotEmpty(String value, String parameterName) +9256093
   System.Data.Entity.DbContext..ctor(String nameOrConnectionString) +34
   mobSocial.Data.Database.DatabaseContext..ctor(String nameOrConnectionString) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Data\Database\DatabaseContext.cs:12
   mobSocial.WebApi.Configuration.Database.DatabaseContextManager.GetDatabaseContext() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Database\DatabaseContextManager.cs:13
   DryIoc.Scope.TryGetOrAdd(Int32 id, CreateScopedValue createValue) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:7125
   DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:7104
   DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, Boolean ifUnresolvedReturnDefault, Type requiredServiceType, RequestInfo preResolveParent, IScope scope) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:493
   DryIoc.Container.ResolveAndCacheDefaultDelegate(Type serviceType, Boolean ifUnresolvedReturnDefault, IScope scope) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:526
   DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Boolean ifUnresolvedReturnDefault) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:452
   DryIoc.Resolver.Resolve(IResolver resolver, IfUnresolved ifUnresolved) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:4310
   mobSocial.Data.EntityRepository`1._SetupContexts() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Data\EntityRepository.cs:34
   mobSocial.Data.EntityRepository`1.Get(Expression`1 where) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Data\EntityRepository.cs:56
   mobSocial.Core.Services.BaseEntityService`1.Get(Expression`1 where, Expression`1 orderBy, Boolean ascending, Int32 page, Int32 count) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Services\BaseEntityService.cs:125
   mobSocial.Services.Settings.SettingService.FurnishInstance(T settingsInstance) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Services\Settings\SettingService.cs:89
   mobSocial.Services.Settings.SettingService.LoadSettings(T settingsObject) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Services\Settings\SettingService.cs:75
   mobSocial.WebApi.Configuration.Infrastructure.<>c__DisplayClass0_0.<RegisterDependencies>b__2(IResolver resolver) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Infrastructure\DependencyRegistrar.cs:70
   DryIoc.<>c__DisplayClass18_0.<RegisterDelegate>b__0(IResolver r) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:3975
   DryIoc.<>c__DisplayClass23_2.<ApplyReuse>b__2() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:5975
   DryIoc.SingletonScope.GetOrAddItem(Object[] bucket, Int32 index, CreateScopedValue createValue) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:7391
   DryIoc.SingletonScope.GetOrAdd(Int32 id, CreateScopedValue createValue) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:7282
   DryIoc.Factory.ApplyReuse(Expression serviceExpr, IReuse reuse, Boolean tracksTransientDisposable, Request request) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:5974
   DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:5901
   DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:6421
   DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:5877
   DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:6041
   DryIoc.Container.ResolveAndCacheDefaultDelegate(Type serviceType, Boolean ifUnresolvedReturnDefault, IScope scope) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:528
   DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Boolean ifUnresolvedReturnDefault) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:452
   DryIoc.Resolver.Resolve(IResolver resolver, IfUnresolved ifUnresolved) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\DependencyManagement\DryIoc\Container.cs:4310
   mobSocial.Core.Infrastructure.AppEngine.mobSocialEngine.Resolve(Boolean returnDefaultIfNotResolved) in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Libraries\mobSocial.Core\Infrastructure\AppEngine\mobSocialEngine.cs:26
   mobSocial.WebApi.Configuration.Infrastructure.ApplicationContext..ctor() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Infrastructure\ApplicationContext.cs:30
   mobSocial.WebApi.Configuration.Infrastructure.ApplicationContext.get_Current() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Infrastructure\ApplicationContext.cs:99
   mobSocial.WebApi.Configuration.Middlewares.<<UseMobAuthentication>b__0_0>d.MoveNext() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Middlewares\MobAuthenticationMiddleware.cs:17
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   mobSocial.WebApi.Configuration.Middlewares.<<UsePictureSizeRegistrar>b__0_0>d.MoveNext() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Middlewares\PictureSizeRegistrar.cs:20
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +777
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +204
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +777
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +777
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +777
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
   mobSocial.WebApi.Configuration.Middlewares.<<UseInstallationVerifier>b__0_0>d.MoveNext() in C:\Users\TBP-1\Downloads\mobsocial-development\mobsocial-development\Presentation\mobSocial.WebApi\Configuration\Middlewares\InstallationVerifierMiddleware.cs:26
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +204
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +14139120
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +194
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +96
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +363
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +157

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1586.0

**Comment by wittyansh** [comment]
Not able to reproduce. Please re-open if issue persist.
