### ISSUE TITLE
Real time chat

### ISSUE THREAD

**Issue by uzair-rm** [mobsoftware/mobsocial#27]
Chat is the most used feature in any social network platform. I think it is missing from mobsocial. Not an issue but an important requirement.

**Comment by wittyansh** [comment]
You are right and thats why we already have [one](https://github.com/mobsoftware/mobsocial/commit/fe6ade2cf533c360f4ed88e3141a4d1762490d30) :)

**Comment by mobsoftware** [comment]
Thanks uzair-rm for the inquiry. We've added Chat to the description features section. Please add more issues if you have any other suggestions.
