### ISSUE TITLE
Getting error when setting up mobsocial

### ISSUE THREAD

**Issue by PatelVish** [mobsoftware/mobsocial#28]
Hi,

When i try to setup the mobsocial, i am getting the error when attempting to setup the db.
![image](https://cloud.githubusercontent.com/assets/2691184/25570801/6019fd12-2df6-11e7-93f7-b42113b81b49.png)

Any help would be appreciated.

I have not made any modification to the code after forking the repo. Everything compiled fine.
However when setting up connection and clicking on test connection logs this error on UI and the one above in Event log.
![image](https://cloud.githubusercontent.com/assets/2691184/25570909/82c3e7d2-2df7-11e7-9528-da82ec698628.png)

**Comment by dobdev** [comment]
Hi, I'm having the same trouble, today after my work i will test a new credential on SQL Express

**Comment by wittyansh** [comment]
Hi, We are in the process of some code merge for our nopCommerce plugin and this mobSocial standalone application. One of the change was moving from automatic migrations to manual ones. And this is what is causing this issue of yours.

For one thing, to test current things, I would suggest you to run the code from the temporary merge branch (https://github.com/mobsoftware/mobsocial/tree/code-merge-development)

BTW, the issue that I can see from your event log is related to migration configuration. You just need to make sure that the configuration file looks like https://github.com/mobsoftware/mobsocial/blob/code-merge-development/Libraries/mobSocial.Data/Migrations/Configuration.cs#L12-L20

Let me know if that solves the issue.

**Comment by PatelVish** [comment]
Thanks @wittyansh i applied the migrations task fix and seems to have done the trick.
