### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by unsorted01** [mobsoftware/mobsocial#29]
Hi guys.. Your app looks amazing and I try to install it because I am very interesting to see your work... But I am facing a big problem to install it... I have followed all the steps descripted here https://github.com/mobsoftware/mobsocial/wiki/How-to-install-mobSocial%3F but nothing happened when i open my install page...

Especially I use VS 2017 Community, but I dont think thats the problem.... 

Step1:
I have downloaded the latest version and also 2-3 earliers versions to check if thats the problem.

Step2:
I build the two projects:
 -Presentation\mobSocial.WebApi
 -Plugins\mobSocial.Plugins.OAuth
and in webpack task runner I Run-Development but it throws a syntax error in skils controller. I fix it and run it again.
Is there anything else to do?

Step 3:
I have installed URL Rewrite in IIS. I follow exactly your steps. The only thing is tha on this screen:
https://github.com/mobsoftware/mobsocial/raw/development/docs/images/iis_2.jpg in Τest Settings in the seccond parameter "Authorization" I get a yellow warning, but I dont think thats the problem, is it?

Step 4:
The same warning in Test Setting as Step3.

Step 5:
I did exactly what you describe.

Step 6:
When I visit my url: http://mobdemo.localhost.com/install nothing happened. ERR_NAME_NOT_RESOLVED

Are you sure that a newbie when followed exactly the steps you described will open your application?
I am asking you that because I followed exactly those steps but nothing happened and I cant understand what am I missing or what I have to know more?
Your application looks amazing and will be a very useful plugin for a lot of web applications thats why I found you and ask your help.....

Thanks in advance

**Comment by wittyansh** [comment]
Hi,
Did you change host name in your hosts file as mentioned in step 3? This is crucial for domain mapping to work.

**Comment by unsorted01** [comment]
Hello and thanks for your quick answer,
yes I did chane the name... After a lot of efforts I can go to installation page using the traditional way : "localhost:xxxx/install" but when i configure the database it throws me an error:  "Failed to connect to the database. Please check values and try again."
Especially I use:
-Database Server : "MYPCNAME\SQLEXPRESS"
-Database Name "mobsocialdemo"
-Database User "MYPCNAME\MYWINDOWSUSER"
-Database Password: empty (I have no password in windows)

In SQL Server Managmement studio the Server Name and User are the same as above. I have tried all the possible combinations. Also the Connection string doesnt work and I check yor solution: https://github.com/mobsoftware/mobsocial/issues/28

I have tried a lot of your last commits in code-merge-development and in development branch. Is there any stable and tested version that you can suggest me to try?

Anyway thanks for your interest... I really think your effort is very good and it is a pity to be so difficult from an extrenal user to use it.

Thanks in advance

**Comment by wittyansh** [comment]
Thanks, I agree. We're still working on it so it'd be easy to install.
Can you check the event log to see if there are any errors?

**Comment by unsorted01** [comment]
The error is that:
POST-?>http://localhost:59082/api/install/test-connection net::ERR_CONNECTION_REFUSED

I still believe that the big problem is setting up the site in IIS because there will be some (maybe easy for you) setting that someone dont know.
So if you try to set up srom start the app in IIS and just tell me what to do exactly step-by-step I am sure that it will work for a lot of users....

Thans again wittyansh

**Comment by unsorted01** [comment]
Or is there a way to install the app without using IIS...
An can you create a database from the migration like this: "dotnet ef database update"

**Comment by wittyansh** [comment]
We've not yet moved to core, so database will have to be supplied for now.
However you can try to install by directly sending a post request to /api/install endpoint with parameters as declared in https://github.com/mobsoftware/mobsocial/blob/development/Presentation/mobSocial.WebApi/Models/Installation/InstallationRequestModel.cs

**Comment by wahbah** [comment]
@wittyansh  I like your project  and wanna see your demo ,i tried to send post request with this parameter
could you told me whats the problem ???  
![1](https://user-images.githubusercontent.com/2452354/37937245-23a007e8-3159-11e8-8f53-0606df1b10b1.PNG)
the response was this message 
![3](https://user-images.githubusercontent.com/2452354/37937252-324ce95a-3159-11e8-80b7-8a1605096f68.PNG)

**Comment by anandmohan847** [comment]
I have followed all the steps descripted here https://github.com/mobsoftware/mobsocial/wiki/How-to-install-mobSocial%3F  when i visit my url http://www.mobdemo.localhost.com/  but nothing happened its return 
 This site can’t be reached
