### ISSUE TITLE
Not able to determine the target market.. Is this a Facebook rival script?

### ISSUE THREAD

**Issue by ubuntume** [mobsoftware/mobsocial#31]
Not to sound ugh, I am looking for a social network script that is open source to actually modify and contribute back. I just wasn't sure where it was going as well as put in a request.

Request. Before it gets to far - don't let it look like facebook #please.

**Comment by mobsoftware** [comment]
Hey ubuntume. Thanks a lot for the suggestion and feel free to contribute.
We would appreciate any contributions. We have a different vision from
Facebook so don't worry it won't be like that :)

-Bruce
