### ISSUE TITLE
Some features are not working after install

### ISSUE THREAD

**Issue by jeandomagni** [mobsoftware/mobsocial#32]
Hey guys,
I was able to install this product with no issues following the instructions on the wiki page.
After install, some of the features are not working as indicated.

The search is not working, I cant add friends or received friends requests, lots of links with no actions. You click them and nothing happens.

I am wondering if I am missing anything.  Can you help?

Thanks

**Comment by wittyansh** [comment]
Hi,
Can you please check if there are any errors in the developer console of your browser?
Also are you facing any UI rendering issues as well?

**Comment by F0rc0sigan** [comment]
Hello,

I also getting same issues. 

1. Dashboard: 
http://take.ms/psS3n
http://take.ms/PFYit
2. When i try to upload image:
http://take.ms/5MJFJ
I get this
http://take.ms/YPq4y
Response:
`{"message":"An error has occurred.","exceptionMessage":"A generic error occurred in GDI+.","exceptionType":"System.Runtime.InteropServices.ExternalException","stackTrace":"   at System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)\r\n   at mobSocial.Services.MediaServices.MobSocialImageProcessor.WriteBytesToImage(Byte[] imageBytes, String filePath, ImageFormat imageFormat) in C:\\Work\\mobsocial\\mobsocial\\Libraries\\mobSocial.Services\\MediaServices\\MobSocialImageProcessor.cs:line 15\r\n   at mobSocial.Services.MediaServices.MediaService.WritePictureBytes(Media picture, MediaSaveLocation pictureSaveLocation) in C:\\Work\\mobsocial\\mobsocial\\Libraries\\mobSocial.Services\\MediaServices\\MediaService.cs:line 194\r\n   at mobSocial.WebApi.Controllers.MediaController.UploadPictures() in C:\\Work\\mobsocial\\mobsocial\\Presentation\\mobSocial.WebApi\\Controllers\\MediaController.cs:line 134\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}`
I am getting same error if i try to upload avatar image from admin.
3. Search
If i type anything in search or press enter, then nothing happens in console. No requests or errors.
4. Links
http://take.ms/sh1iD
5. http://take.ms/9jBdR
6. In admin. If i do search and enter aything it redirects me on '/'

**Comment by wittyansh** [comment]
Hi, 
Thanks for providing with your inputs.
1. [Fixed](https://github.com/mobsoftware/mobsocial/commit/f43eee92eb3020dfb31bad58d804c9eb44dc9835)

2. This usual happens if the upload directory doesn't exist. Added a [check](https://github.com/mobsoftware/mobsocial/commit/b6133535de6750fce7749b03eb94b50e8fce5979) for that. Also added a few media api [fixes](https://github.com/mobsoftware/mobsocial/commit/4f6236772641cab575b9199cfcdd9499a83b28fc)

3. The user dashboard links and search are not yet complete. The links will be functional when done.

Thanks,
Anshul
