### ISSUE TITLE
Error Failed to connect to the database. Please check values and try again. 

### ISSUE THREAD

**Issue by Mo-GH** [mobsoftware/mobsocial#40]
the configration is right and the Database and user are right too??

![2018-02-22 21_40_26-](https://user-images.githubusercontent.com/34102804/36563002-1581a30a-1819-11e8-91ad-4883f4994169.png)

**Comment by machocr** [comment]
I'm getting the same issue.  
It's trying to read the plug ins code in api application when it is in app project.   If you manually set the right plug in location, then you get a null connection string reference error.
It looks like the application was refactored, so some file locations have changed, or the names are different.

**Comment by Dannillo** [comment]
same to me. Unable to connect to the database at this step.

**Comment by wittyansh** [comment]
Hi,
Thanks for reporting. The issued should be [fixed](https://github.com/mobsoftware/mobsocial/commit/14cf0ce8cbafa482ccc5f0b77c351553bede619b) now.

**Comment by Dannillo** [comment]
Not for me :-( same problem.
i used ./sqlexpress , <pcname>/sqlexpress, IP, etc. 
nothing worked yet. sql management connects successful, so the database should not be the problem. any ideas ?

**Comment by Dannillo** [comment]
![unbenannt](https://user-images.githubusercontent.com/37112018/37044931-0b27eaf4-2165-11e8-9d76-21cfdafbf253.png)

**Comment by wittyansh** [comment]
Can you see if there is any error from Chrome Developer Console and the response of the request for test connection?

**Comment by wahbah** [comment]
Hello friend @wittyansh  I download new fix , and cheeked chrome console and give me three errors
 
![1](https://user-images.githubusercontent.com/2452354/37437277-f1587cc4-27f4-11e8-8b23-790d3bc24eb2.PNG)
![2](https://user-images.githubusercontent.com/2452354/37437278-f17c7e12-27f4-11e8-8e1c-6d322100d9ac.PNG)
, i would inform your i add app pool identity permission to web config

**Comment by wittyansh** [comment]
@wahbah Your issue is different. See https://stackoverflow.com/a/12867753

**Comment by wittyansh** [comment]
Closing this now. Reopen if the install issue is not fixed.

**Comment by wahbah** [comment]
thanks, @wittyansh  I did as you said , but I got another erorr : 
![image](https://user-images.githubusercontent.com/2452354/37490936-db2b76b2-28a4-11e8-9d5f-5ac6680128f3.png)

**Comment by mobsoftware** [comment]
Hi wahbah,

It says that the directory is not found. Can you try the path listed in the
exception using Windows Explorer and see if you can access it?

Thanks,
Bruce

**Comment by wahbah** [comment]
But as you see in original project not have this directory

**Comment by wahbah** [comment]
@wittyansh hi friend , Can you help me to setup this project I would like to learn more from your project and your approche .. I can't install it , could you contact with me and guid me..

**Comment by wahbah** [comment]
@mobsoftware  I try to install  mobsocial master version and get error " failed to connect to database  "
and get error in console message 
![image](https://user-images.githubusercontent.com/2452354/37803378-14771e2a-2e37-11e8-9f73-8b390e9a6b71.png)
