### ISSUE TITLE
Getting error: Could not find a part of the path \Presentation\mobSocial.WebApi\Plugins'.'

### ISSUE THREAD

**Issue by sourabhsomani** [mobsoftware/mobsocial#44]
I am getting this error when I am running api. Error is coming in following line.

```C#
var pluginFiles = probeDirectory.GetFiles("plugin.config", SearchOption.AllDirectories);
```

This line is exists in **GetAllPluginsInfos** in this method

**File path**
\Libraries\mobSocial.Core\Plugins\PluginConfigurator.cs

Could you please help me how can I resolve this issue. 

Thank You
👍

**Comment by wittyansh** [comment]
Can you try creating mobSocial.WebApi\Plugins directory?

**Comment by sourabhsomani** [comment]
Yeah Done thank You bro :)
